# Generated by Django 2.2.5 on 2022-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(default='', max_length=300, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git',
            field=models.CharField(max_length=60, verbose_name='깃허브 주소'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.CharField(max_length=40, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumnail_img',
            field=models.ImageField(upload_to='', verbose_name='썸네일 이미지'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='제목'),
        ),
    ]
