# Generated by Django 2.2.5 on 2022-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20220313_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='desc',
            field=models.TextField(max_length=300, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='semester',
            field=models.CharField(choices=[('1학기', '1학기'), ('2학기', '2학기')], default='', max_length=10, null=True, verbose_name='학기'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='thumnail_img',
            field=models.ImageField(default='', upload_to='', verbose_name='썸네일이미지'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='challenge_comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
